dist: xenial
sudo: required
language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - dev-travis-migration

before_install:
  - "cp travis/.travis.settings.xml $HOME/.m2/settings.xml"

install: travis_retry mvn install -DskipTests=true -B -V

stages:
  - build
  - release

env:
  global:
    # Release version has to start with real version (14-....) for the docker image to build successfully.
    - RELEASE_VERSION=13
    - DEVELOPMENT_VERSION=14-SNAPSHOT


jobs:
  include:
    - name: "Build"
      stage: build

    - name: "Push to Nexus"
      stage: release
      install: skip
      if: type != pull_request AND commit_message ~ /\[release\]/
      script: travis_wait 40 bash travis/release.sh
