name: Alfresco Super POM CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

env:
  MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
  GIT_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
  GIT_PASSWORD: ${{ secrets.BOT_GITHUB_TOKEN }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  RELEASE_VERSION: "13"
  DEVELOPMENT_VERSION: "14-SNAPSHOT"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.0.0
      - name: "Build"
        run: mvn -B -V install

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: build
    if: >
      github.ref_name == 'master' &&
      github.event_name != 'pull_request' &&
      contains(github.event.head_commit.message, '[release]')
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v7.0.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.0.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/configure-git-author@v7.0.0
        with:
          username: ${{ secrets.BOT_GITHUB_USERNAME }}
          email: ${{ secrets.BOT_GITHUB_EMAIL }}
          global: true
      - name: "Release"
        run: bash ci/release.sh